agent:
  log_path: /var/log/ebpf-security-agent/events.log
  heartbeat_interval_sec: 5

xdp:
  xdp_enable: true
  xdp_interface: enp0s3
  xdp_mode: skb
  xdp_object_path: /opt/ebpf-security-agent/bpf/xdp_filter.bpf.o
  xdp_stats_interval_sec: 5
